project:
  type: website
website:
  title: "Blog"
  listing: 
    categories: true
  reader-mode: true
  page-footer: "Copyright 2022, Damon C. Roberts"
  open-graph: true
format:
  html:
    theme: journal
    code-copy: true
    css: styles.css
    toc: true